menu:
  首页: /
  关于: /about
  归档: /archives
  RSS: /atom.xml


widgets:
- search
- category
- tagcloud

excerpt_link: 阅读全文

twitter:
  username: dorayox
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
feed: 
  type: atom
  path: atom.xml
  limit: 20


comment_provider: facebook
# Facebook comment
facebook:
 appid: yomingyo@gmail.com
 comment_count: 5
 comment_width: 840
 comment_colorscheme: light